# Site
name: "Joep Verhaeg"
title: "Everything is connected!"
description: "Explore my smart home adventure"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: https://docs.joepverhaeg.nl
google_analytics: 'UA-348944-1'
disqus:
mailchimp-list: 'https://joepverhaeg.us20.list-manage.com/subscribe/post?u=78f77b09ec5fd42dd902c33c1&amp;id=18d30006e8'
include: ["_pages"]
permalink: /:title/
email: info@joepverhaeg.nl

# Authors
authors:
  joep:
    name: Joep Verhaeg
    display_name: Joep
    avatar: 'assets/images/avatar-joep.png'
    email: info@joepverhaeg.nl
    linkedin: https://www.linkedin.com/in/joepverhaeg/
    github: https://www.github.com/joepv/
    description: "Owner and author of this smart home blog!"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]